[project]
name = "learndeepagents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nupur Maheshwari", email = "nupur.maheshwari.2010@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "deepagents>=0.7.23",
    "ipykernel>=7.4.0",
    "langchain>=1.4.3",
    "python-dotenv>=1.2.4",
    "tavily-python>=0.8.5",
]

[project.scripts]
learndeepagents = "learndeepagents:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
